name: Run tests on every pull request

on:
  pull_request:

jobs:
  tests:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9, 3.10, 3.11, 3.12 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-cov

      - name: Run pytest with coverage (require 100%)
        run: |
          # By default this measures coverage for the repo root.
          # If you have a package directory (e.g. `quizapp`), replace --cov=. with --cov=quizapp
          pytest --maxfail=1 --disable-warnings -q \
            --cov=. \
            --cov-report=term \
            --cov-report=xml \
            --cov-fail-under=100

      - name: Upload coverage XML (always, for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: coverage.xml